### ISSUE TITLE
bug in windows 10!

### ISSUE THREAD

**Issue by acerdevs** [mishakorzik/py-ddoser#2]
api.proxyscrape.com/v2/?request=displayproxies&amp;country=ru.</p> good! Starting...
Found 263 new proxies

**Comment by mishakorzik** [comment]
tell about the error in more detail

**Comment by acerdevs** [comment]
i a start  a programm and  writing:
api.proxyscrape.com/v2/?request=displayproxies&country=ru.

good! Starting...
Found 263 new proxies 
always

**Comment by mishakorzik** [comment]
you need to specify the site on which you want to launch an attack, not a proxy link
